### ISSUE TITLE
Webhooks are not being created after launched

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#105]
The GitHub webhooks are no longer being created when a booster is launched. 

Initially reported by @ia3andy

**Comment by ia3andy** [comment]
It seems the bug is still reproducible on https://developers.redhat.com/launch/
but I can't reproduce it locally with the current "master" code base.
Let's wait to check on the next release to close this issue.

**Comment by ALRubinger** [comment]
Also worth checking the logs on the launch prod service.

On Feb 16, 2018 9:58 AM, "Andy Damevin" <notifications@github.com> wrote:

It seems the bug is still reproducible on https://developers.redhat.com/
launch/
but I can't reproduce it locally with the current "master" code base.
Let's wait to check on the next release to close this issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabric8-launcher/launcher-planning/issues/105#issuecomment-366191638>,
or mute the thread

**Comment by gastaldi** [comment]
Fixed in production
