### ISSUE TITLE
Return list of dependencies for a booster

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-planning#124]
In order for the analytics to perform analytics on the boosters it will need to have a list of the dependencies for the specific booster. Extend the booster catalog endpoint to also include a list of dependencies and the '/launch' endpoint to input extra dependencies that the user selected on the "dependency screen"

**Comment by quintesse** [comment]
I'd actually suggest a different endpoint perhaps, specifically for obtaining dependencies?

Because obtaining booster info is a relatively "cheap" action, the moment we've read the booster catalog (which is fast) we have all the info about a booster. For the dependency info however we need to have the booster repository itself available (clone it if it isn't yet) and then read and parse the pom file. SO perhaps it would be a good idea to split those two operations?

**Comment by gastaldi** [comment]
Yes, a separate endpoint is a good idea. /Booster is now used to return metadata information about the booster. Maybe something like `/booster-catalog/booster/dependencies`?

**Comment by edewit** [comment]
@quintesse the boosters are already cloned on startup right, the analytics can also work on a git repo url so we could also opt for adding the booster repo url to the `/booster-catalog/booster` endpoint

**Comment by quintesse** [comment]
@edewit they are not actually. It's all done asynchronously these days, The only thing we still do in production is that we start up a second thread that downloads them just so they'll be ready. But that's just an option.

**Comment by quintesse** [comment]
For example, if at some point we really get a lot of community contributions I think it could become impractical to start downloading them all all of the time. Especially when we don't need them until someone actually gets to the end of the wizard and clicks launch. (Because nowadays all the necessary information is in the catalog, there's nothing of interest anymore in the booster itself UX-wise)

**Comment by edewit** [comment]
Okay then in that case let's just add the repo url to the result so the analytics can fetch the pom strait out of github.
