### ISSUE TITLE
Introduce an Operator for installing the Launcher

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#195]
This should install the same objects as specified in the template in  https://github.com/fabric8-launcher/launcher-openshift-templates/blob/master/openshift/launcher-template.yaml

**Comment by quintesse** [comment]
Btw, if that's all it does what's the advantage? Isn't the idea of an Operator that you can code complex installation/setup decisions into code?

In my opinion the effort of writing and maintaining an Operator should be outweighed by the advantages it brings, otherwise we could just as easily stick with the template.

(Just mentioning this here to get a discussion going on this subject. I have nothing against creating an Operator as long as it gives us some measurable benefit)

**Comment by gastaldi** [comment]
There are several environment variables and they need to be defined
according to the kind of installation you are looking for.

IMHO with an operator you can specify a custom CRD containing only the
parameters you need to create the launcher (with/without Keycloak,
Openshift impersonation, Gitea as the default git provider, etc) and the
operator code would have the necessary logic to install our services
without having to browse dozen of parameters as we have now in the template

**Comment by quintesse** [comment]
Won't you need to specify most of those variables anyway?

And isn't looking at a template with a dozen parameters or looking at the docs of our Operator describing the same dozen parameters basically the same thing? But instead of maintaining a text file we now need to maintain code that needs special permissions on a cluster to be installed etc etc

I know I'm being difficult here but I assure you I'm not doing it on purpose! I just keep failing to see the advantage 😅 

For example Operators seem perfect to me in the case of @ia3andy 's example Operator that he made during his course, something that dynamically assures that you have the right number of Pods running and starts a new one whenever a Pod  crashes etc. And perhaps complex software like web servers and databases are also helped by using Operators. But I wish somebody would explain to me the advantage in our case which is just pretty simple and very static.

I know @ia3andy has some ideas about this too so perhaps he can come up with some ideas.
(And again, I won't vote against creating an Operator if that's what others really want. I'm just trying to understand the possible justifications)

**Comment by ia3andy** [comment]
@quintesse I agree that an operator just to "enable" a feature seems useless. There will be not a lot of logic inside it, it should not be hard to maintain. The operator will use the existing template which will reduce the quantity of code to maintain. 

I see some more reason it could be interesting to have an operator for the Launcher:
- The integ8ly team has nearly all their available features as operator (ex: Gitea, KC). So having one for the Launcher makes it more uniform for them
- In the near future the operator SDK should give a way for deeper (UI) integration in the openshift console. In which case we would already be ready to make the Launcher use it.
- I have the feeling that the [OLM](https://github.com/operator-framework/operator-lifecycle-manager) will be some kind of "App store" for Openshift in the future. Having our own operator may be yet another way to highlight our Launcher.

Therefore, I think it's worst a first version. It's not a huge effort to create it and it gives at the same time a way for me to interact a bit more with the operator SDK. 

If we find it to be useless and a pain in the near future. We can just through it away..

**Comment by ia3andy** [comment]
Closing
