### ISSUE TITLE
Support for Emergency Response Demo Scenario

### ISSUE THREAD

**Issue by johnfriz** [fabric8-launcher/launcher-planning#212]
Allow the NAPS Emergency Response Demo Project to be "one click" deployed by Launcher.

https://github.com/NAPS-emergency-response-project

**Comment by gastaldi** [comment]
According to the meeting I had with @johnfriz and S.M. Shaaf, using Launcher to deploy the NAPS demo would only work on clusters that already have the backend set up. Launcher needs to be able to provision backend services (AFAIR operators are not being used, so CRDs cannot be applied in the current scenario). I created https://github.com/fabric8-launcher/launcher-planning/issues/215 for that matter.

Due to their short timeframe it was decided to implement that deployment using Ansible scripts and revisit the idea of using Launcher to provision the NAPS Emergency Response Demo after summit.

I'm keeping this issue open so we can have a common place to discuss about the necessary requirements in Launcher to support this scenario after summit.

**Comment by ALRubinger** [comment]
> Due to their short timeframe it was decided to implement that deployment using Ansible scripts and revisit the idea of using Launcher to provision the NAPS Emergency Response Demo after summit.

I'd like to push back on this a little bit to ensure that's the necessary course of action. :)  Launcher's stated purpose is to handle one-click deployment, so I'm wondering what pieces of NAPS demo cannot be represented by OpenShift templates on a known cluster (RHMI), and what gaps we'd need to fill for things to work here.

In other words, this is where we have a chance to let customer use cases drive development so if we can make it all fit in reasonable timeframe, that'd be my preference for prioritized development.

**Comment by gastaldi** [comment]
As in https://github.com/fabric8-launcher/launcher-backend/commit/97fa7b95d9a75ab6eadc0a2b85c8ba03fcb9b94b we no longer require a target Git repository when launching an application. 

As I also mentioned in the meeting, if the application to be deployed can be described as a set of templates and they could live in a separate repository (inside an `.openshiftio` directory), we can add it to the [booster-catalog](https://github.com/fabric8-launcher/launcher-booster-catalog) and deploy only the templates, without any GitHub interaction.

**Comment by gastaldi** [comment]
Closing for now, will revisit later
