### ISSUE TITLE
Testing Strategy: Boosters to use ARQ Cube

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#43]

**Comment by rhoads-zach** [comment]
@ALRubinger please let us know as you incorporate ARQ Cube into testing. We can consider adding an enhancement issue to docs to explain ARQ Cube and link to more details.

FYI @inoxx03 @tradej @lavernw1

**Comment by Ladicek** [comment]
CC @RadekKoubsky

**Comment by Ladicek** [comment]
CC @spisiakm

**Comment by Ladicek** [comment]
Open issues:

- https://github.com/arquillian/arquillian-cube/issues/633
- https://github.com/arquillian/arquillian-cube/issues/635
- https://github.com/arquillian/arquillian-cube/issues/636
- https://github.com/arquillian/arquillian-cube/issues/743

**Comment by spisiakm** [comment]
Example implementations of ITs using Arquillian Cube can be found here: 
- https://github.com/RadekKoubsky/rest_springboot-tomcat/tree/arquillian-cube-integration-test-openshift/src/test for spring-boot-http-booster
- https://github.com/spisiakm/vertx-http-booster/tree/arquillian-test/src/test for vertx-http-booster

(Note: these implementations are still WIP)

You can successfully run these tests with `mvn clean fabric8:deploy -Popenshift` and then running `mvn verify -Popenshift-it -Denv.init.enabled=false` after the pod is ready (if you do `mvn clean fabric8:deploy -Popenshift && mvn verify -Popenshift-it -Denv.init.enabled=false` , the tests will fail because the route is still somehow not ready even though we have waiting for readiness implemented)

However, ideally, we would like to just run `mvn clean verify -Popenshift,openshift-it` to successfully build image stream, deploy it to specified namespace and run the tests. This is not possible for now (tested with latest version of arq cube - 1.7.0) as the tests will fail because the image stream built by fabric8 maven plugin strangely disappears from openshift just before arquillian wants to deploy it and start the tests.

The above mentioned failure is our main concern now (as I'm sure there will still be some major/minor issues after this is resolved).

**Comment by rdruss** [comment]
Ok, is there an interim plan on how testing will be done until the ARQ Cube issues are resolved?  I see 2 distinct cases:

- What is done in the test suite for evaluate release quality
- What is done in boosters to demonstrate to users how they should be testing

**Comment by Ladicek** [comment]
Well the interim plan is `OpenShiftTestAssistant` and the tests in ithe boosters, for both items. For the 1st, we'll obviously be doing license checks.

**Comment by rdruss** [comment]
This sounds reasonable to me.  The decision is to continue using OpenShiftTestAssistant (OTA) for both scenarios listed until ARQ Cube has sufficiently addressed the issues.  The evaluation function for determining whether we're ready to switch is to Martin's example test listed above.

**Comment by Ladicek** [comment]
Just as a status update, after re-verification, these issues are still open:

Open issues:

- https://github.com/arquillian/arquillian-cube/issues/633
- https://github.com/arquillian/arquillian-cube/issues/743

Out of these 2, https://github.com/arquillian/arquillian-cube/issues/743 is a blocker.

**Comment by spisiakm** [comment]
Just wanted to give an update on this:
[arquillian/arquillian-cube#743](https://github.com/arquillian/arquillian-cube/issues/743) has been resolved and the Arquillian guys released a new version of Arquillian Cube with this fix - 1.9.0. Next week I'm going to try getting it working with ConfigMap booster.

**Comment by Ladicek** [comment]
To expand on what @spisiakm said: we've verified that Cube 1.9.0 is enough for simple boosters like http or health check, and will have PRs for those this week (hopefully :-) ). We'll be looking at CRUD and ConfigMap next.

**Comment by Ladicek** [comment]
I have PRs open for all Swarm boosters (except of SSO, which is undergoing much bigger changes). Vert.x is work in progress by @spisiakm and on Spring Boot front, I believe @alesj is working on this as well.

**Comment by bartoszmajsak** [comment]
If this is closed @gastaldi does it mean we are with non-trivial boosters too?

**Comment by gastaldi** [comment]
@bartoszmajsak not sure what non-trivial boosters are you referring to, but I believe they should all run Arquillian Cube too.
